### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by PyDataBlog** [xiaodaigh/julia-data-science-base-docker-img#1]
Really cool concept but the project seems abandoned since that latest build [fails](https://hub.docker.com/redirect/?resource_uri=/api/audit/v1/action/bfa710ac-65a4-4491-8876-64fa8d32881e/). Is that the case?

**Comment by xiaodaigh** [comment]
Didn't realise it fails. This is kinda build once and leave it kinda image. Docker cant build it as it needs lots of RAM. Build it yourself or use it as a base.

**Comment by xiaodaigh** [comment]
I will close this as it builds for me OFFLINE just not on docker hubs (due to RAM constraints). Please open an issue if you need help.
